#!/bin/busybox ash

. /etc/init.d/tc-functions
. /var/www/cgi-bin/pcp-functions

useBusybox
TARGET=`cat /etc/sysconfig/backup_device`
tce-load -i ca-certificates.tcz
tce-load -wi pcp-shairportsync.tcz avahi.tcz libavahi.tcz glib2.tcz pcp-libffmpeg.tcz pcp-libsoxr.tcz

cd /mnt/$TARGET/optional
rm pcp-shairportsync.tcz*

wget -O pcp-shairportsync.tcz https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/pcp-shairportsync2.tcz
wget -O pcp-shairportsync.tcz.md5.txt https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/pcp-shairportsync2.tcz.md5.txt
wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/pcp-shairportsync.tcz.dep
wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/libconfig_popt.tcz
wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/libconfig_popt.tcz.md5.txt
# wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/libplist.tcz
# wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/libplist.tcz.md5.txt
wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/libsodium.tcz
wget https://raw.githubusercontent.com/sam0402/pCP-addon/main/AirPlay2/libsodium.tcz.md5.txt

sed -i '/ldconfig/d' /opt/bootlocal.sh
echo ldconfig >>/opt/bootlocal.sh
echo "Rebooting..."
sleep 3
pcp br
